# Generated by Django 2.1.7 on 2019-09-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_person_profile_app_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
